### ISSUE TITLE
Ecowitt sensor name

### ISSUE THREAD

**Issue by drc38** [home-assistant-libs/aioecowitt#13]
Hi, in HA I've just switched over from https://github.com/garbled1/homeassistant_ecowitt to your integration. It's working well however with the automatic sensor prefix `easyweatherv1_6_4_` the transition will not be seamless with my existing sensors/statistics which do not have a prefix (eg sensor.dewpoint). Also because it includes the firmware version a similar problem may occur when the firmware updates. Is there a way to provide a custom (or exclude) sensor prefix?

**Comment by pvizeli** [comment]
This is not the issue from the library, more like HA handle it. It is also not the firmware version, it's the hardware version
